#!/usr/bin/env ruby
# 
#  setup_dns
#  slicehostAPI
#  
#  Created by Caius Durling on 2008-11-26.
#  Copyright 2008 Caius Durling. All rights reserved.
# 
#  Sets up records for a new domain
# 

ARGV = [
  "--domain=aaacaiusistesting.com",
  "--ip-address=208.78.100.145",
  # "--google=blahblahblah",
  # "--quiet",
  # "--help",
  # "--version",
]

require File.join(File.dirname(__FILE__) + "/../config/boot.rb")
require "optparse"
require "ostruct"

class OptParseArgs
  
  def self.parse( args )
    options = OpenStruct.new
    options.domain = ""
    options.ip_address = ""
    options.cname_string = nil
    options.quiet = false
    options.ttl = CONFIG["dns"]["ttl"] || 84600
        
    opts = OptionParser.new do |opts|
      opts.banner = "Usage: ruby script/setup_dns [options]"

      opts.separator ""
      opts.separator "Specific options:"

      # Required Arg: Domain name
      opts.on("-d", "--domain DOMAIN", String, "Domain name") do | domain |
        options.domain = domain
      end
      
      # Required Arg: IP Address of slice
      opts.on("-i", "--ip-address IP_ADDRESS", String, "IP Address of the slice") do | ip |
        options.ip_address = ip
      end
      
      # Optional Arg: Google CNAME verification string
      opts.on("-g", "--google [CNAME_STRING]", String, "Google CNAME Verification String") do | cname_string |
        options.cname_string = cname_string
      end
      
      # Options Arg: TTL
      opts.on("-t", "--ttl [TTL]", Integer, "Time to Live for the records") do | ttl |
        options.ttl = ttl
      end
      
      opts.separator ""
      opts.separator "Common options:"
      
      # Optional Arg: Run quietly
      opts.on("-q", "--quiet", "Run quietly (minimal output)") do | q |
        options.quiet = q
      end
      
      opts.on_tail("-h", "--help", "Show this message") do
        puts opts
        exit
      end
      
      opts.on_tail("-v", "--version", "Show version") do
        puts APP_VERSION
        exit
      end
    end
    
    opts.parse!(args)
    options
  end
end

# Kick it all off
options = OptParseArgs.parse(ARGV)

# Check we have the needed options
if options.domain.empty? || options.ip_address.empty?
  puts "Error: Both domain and ip address are required flags"
  exit(1)
end

p options

# See if the zone already exists
if Zone.find(:first, :params => {:origin => options.domain.periodify})
  puts "Error: Domain already exists in your control panel"
  exit(2)
end

# Create the zone
zone = Zone.new(:origin => options.domain.periodify, :ttl => options.ttl)
zone.save

# Create the records












